name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/zeldaret/ph-build:st

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [eur, jp]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare
        run: |
          mv /extract/* ./extract

      - name: Build
        run: |
          python tools/configure.py -v ${{ matrix.version }} -w wibo --compiler /mwccarm --no-extract
          ninja arm9_${{ matrix.version }} report_${{ matrix.version }} check_${{ matrix.version }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_report
          path: build/${{ matrix.version }}/report_${{ matrix.version }}.json
